export const GET_AIRPLANES = "GET_AIRPLANES";

export const TOGGLE_NEWSLETTER = "TOGGLE_NEWSLETTER";

export const TOGGLE_MOBILE_NAV = "TOGGLE_MOBILE_NAV";
export const TOGGLE_MOBILE_SEARCH = "TOGGLE_MOBILE_SEARCH";
