export const TOGGLE_NEWSLETTER = "TOGGLE_NEWSLETTER";
export const TOGGLE_NAVIGATION = "TOGGLE_NAVIGATION";
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
export const AIRPLANE_SEARCH_TEXT = "AIRPLANE_SEARCH_TEXT";
export const AIRPLANE_SORT = "AIRPLANE_SORT";
export const AIRPLANE_FILTER = "AIRPLANE_FILTER";
export const AIRPLANE_SEARCH_VALUES = "AIRPLANE_SEARCH_VALUES";
