export const TOGGLE_NEWSLETTER = "TOGGLE_NEWSLETTER";
export const TOGGLE_NAVIGATION = "TOGGLE_NAVIGATION";
export const TOGGLE_SEARCH = "TOGGLE_SEARCH";

export const AIRPLANE_SEARCH_TEXT = "AIRPLANE_SEARCH_TEXT";
export const AIRPLANE_SORT = "AIRPLANE_SORT";
export const AIRPLANE_FILTER = "AIRPLANE_FILTER";
export const AIRPLANE_DROPDOWN = "AIRPLANE_DROPDOWN";
export const AIRPLANES_RESET = "AIRPLANES_RESET";
export const AIRPLANE_SEARCH_VALUES = "AIRPLANE_SEARCH_VALUES";
export const COUNTRIES_OPERATORS = "COUNTRIES_OPERATORS";

export const INCIDENT_SEARCH_TEXT = "INCIDENT_SEARCH_TEXT";
export const INCIDENT_SORT = "INCIDENT_SORT";
export const INCIDENT_FILTER = "INCIDENT_FILTER";
export const INCIDENT_DROPDOWN = "INCIDENT_DROPDOWN";
export const INCIDENT_RESET = "INCIDENT_RESET";

export const HOME_LINKS = "HOME_LINKS";
